name: Build Linux Binaries (x86_64 & ARM)

on:
  workflow_dispatch:
  push:
    branches:
      - test/build

jobs:
  build_x86_64:
    name: Build for x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: dataelement/bisheng-telemetry-search
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          path: bisheng-telemetry-search

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          pip install --upgrade pip setuptools wheel
          pip install cython

      - name: Build the project
        working-directory: ./bisheng-telemetry-search/telemetry_search
        run: |
          pwd
          python build_all.py --delete-source
          mkdir ../../build_output
          rm -rf ./build
          cp -r ./* ../../build_output/
          ls -lh ../../build_output/

      - name: Upload x86_64 build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: telemetry_search-x86_64
          path: ./build_output/*

  build_arm:
    name: Build for ARM
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: dataelement/bisheng-telemetry-search
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          path: bisheng-telemetry-search

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          pip install --upgrade pip setuptools wheel
          pip install cython

      - name: Build the project
        working-directory: ./bisheng-telemetry-search/telemetry_search
        run: |
          pwd
          python build_all.py --delete-source
          mkdir ../../build_output
          rm -rf ./build
          cp -r ./* ../../build_output/
          ls -lh ../../build_output/

      - name: Upload ARM build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: telemetry_search-arm
          path: ./build_output/*


  deploy_to_sso_project:
    name: Deploy Artifacts to SSO Project
    needs: [ build_x86_64, build_arm ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SSO Project
        uses: actions/checkout@v2
        with:
          repository: dataelement/bisheng
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          base: feat/2.3.0
          path: bisheng

      - name: Download x86_64 build artifacts
        uses: actions/download-artifact@v4
        with:
          name: telemetry_search-x86_64
          path: ./telemetry_search_x86_64

      - name: Download ARM build artifacts
        uses: actions/download-artifact@v4
        with:
          name: telemetry_search-arm
          path: ./telemetry_search_arm

      - name: copy files
        run: |
          ls -lh ./telemetry_search_x86_64
          ls -lh ./telemetry_search_arm
          
          mkdir ./telemetry_search
          cp -r ./telemetry_search_x86_64/* ./telemetry_search/
          cp -r ./telemetry_search_arm/* ./telemetry_search/
          ls -lh ./telemetry_search
          cp -r ./telemetry_search ./bisheng/src/backend/bisheng/
          ls -lh ./bisheng/src/backend/bisheng/telemetry_search

      - name: Commit and Push changes
        working-directory: ./bisheng
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b feat/2.3.0
          git add .
          git commit -m "chore: update telemetry_search build artifacts [skip ci]" || echo "No changes to commit"
          git push origin feat/2.3.0
          
          
        
          
