name: Build Linux Binaries (x86_64 & ARM)

on:
  workflow_dispatch:
  push:
    branches:
      - test/build

jobs:
  build_x86_64:
    name: Build for x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: dataelement/bisheng-telemetry-search
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          path: bisheng-telemetry-search

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          pip install --upgrade pip setuptools wheel
          pip install cython

      - name: Build the project
        working-directory: ./bisheng-telemetry-search/telemetry_search
        run: |
          pwd
          python build_all.py --delete-source
          mkdir ../../build_output
          rm -rf ./build
          cp -r ./* ../../build_output/
          ls -lh ../../build_output/

      - name: Upload x86_64 build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bisheng-telemetry-search-x86_64
          path: ./build_output/*
          

          
        
          
